AMP_RABBITMQ_URL=localhost; \
AMP_MONGODB_URL=localhost; \
AMP_MONGODB_DBNAME=proofdex; \
AMP_EXCHANGE_CONTRACT_ADDRESS=0x9c446449fbc378941586Ef7a2196B13CC12AEBcd; \
AMP_ETHEREUM_NODE_HTTP_URL=https://rinkeby.infura.io; \
AMP_ETHEREUM_NODE_WS_URL=wss://rinkeby.infura.io/ws; \
AMP_ENABLE_TLS=false; \
fresh
