// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import big "math/big"
import common "github.com/ethereum/go-ethereum/common"

import mock "github.com/stretchr/testify/mock"
import types "github.com/ethereum/go-ethereum/core/types"

// EthereumService is an autogenerated mock type for the EthereumService type
type EthereumService struct {
	mock.Mock
}

// GetBalanceAt provides a mock function with given fields: a
func (_m *EthereumService) GetBalanceAt(a common.Address) (*big.Int, error) {
	ret := _m.Called(a)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(common.Address) *big.Int); ok {
		r0 = rf(a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Address) error); ok {
		r1 = rf(a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingNonceAt provides a mock function with given fields: a
func (_m *EthereumService) GetPendingNonceAt(a common.Address) (uint64, error) {
	ret := _m.Called(a)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(common.Address) uint64); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Address) error); ok {
		r1 = rf(a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitMined provides a mock function with given fields: tx
func (_m *EthereumService) WaitMined(tx *types.Transaction) (*types.Receipt, error) {
	ret := _m.Called(tx)

	var r0 *types.Receipt
	if rf, ok := ret.Get(0).(func(*types.Transaction) *types.Receipt); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*types.Transaction) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
